### PR TITLE
chore: deploy demo to surge.sh

### PR DESCRIPTION
**Pull request by polomani**

### CODE REVIEW

**Comment by polomani** [comment]
Travis automatic deployment: https://101-pr-glimpse-cognitedata.surge.sh

**Review by man-csl — APPROVED** [review]

**Comment by polomani** [comment]
@rumeshwick not sure what's better for you. should I just merge, or you guys will do it yourself?

**Comment by rumeshwick** [comment]
@polomani i will merge this

**Comment by rumeshwick** [comment]
> @rumeshwick not sure what's better for you. should I just merge, or you guys will do it yourself?

I will merge this

**Pull request merged**
